name: Countly
image: ubuntu-14-04-x64
min_size: 512mb
config:
  #cloud-config
  users:
    - name: countly
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
    - sendmail
  runcmd:
    - export HOME=/root/ && cd /var && git clone git://github.com/andrewsomething/countly-server.git && cd countly-server && bash bin/countly.install.sh
