name: Countly
image: ubuntu-14-04-x64
min_size: 512mb
config:
  #cloud-config
  users:
    - name: root
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
    - python-software-properties
    - sendmail
    - supervisor
    - nginx
    - imagemagick
    - iptables
    - build-essential
    - iptables-persistent
  runcmd:
    - cd /var && git clone git://github.com/ar2rsawseen/countly-server.git && cd countly-server && bash bin/countly.do.install.sh
