name: Countly
image: ubuntu-14-04-x64
min_size: 512mb
config:
  #cloud-config
  users:
    - name: root
      groups: sudo
      shell: /bin/bash
      sudo: ['ALL=(ALL) NOPASSWD:ALL']
  packages:
    - git
  runcmd:
    - cd /var && git clone git://github.com/Countly/countly-server.git && cd countly-server && bash bin/countly.install.sh
